version: '3.4'

services:
  roogle.rooglespider:
    image: ${DOCKER_REGISTRY-}rooglerooglespider
    build:
      context: .
      dockerfile: Roogle.RoogleSpider/Dockerfile
    networks:
      - db-net
    secrets:
      - roogle_db_user
      - roogle_db_pass

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - db-net

networks:
  db-net:

secrets:
  roogle_db_user:
    file: ./Secrets/roogle_db_user.txt
  roogle_db_pass:
    file: ./Secrets/roogle_db_pass.txt
