version: '3.4'

services:
  roogle.rooglespider:
    image: ${DOCKER_REGISTRY-}rooglerooglespider
    build:
      context: .
      dockerfile: Roogle.RoogleSpider/Dockerfile
    networks:
      - db-net
    secrets:
      - roogle_db_user
      - roogle_db_pass

  roogle.rooglepageconsumer:
    image: ${DOCKER_REGISTRY-}rooglerooglepageconsumer
    build:
      context: .
      dockerfile: Roogle.RooglePageConsumer/Dockerfile
    networks:
      - db-net
    secrets:
      - roogle_db_user
      - roogle_db_pass

  roogle.roogleurlconsumer:
    image: ${DOCKER_REGISTRY-}roogleroogleurlconsumer
    build:
      context: .
      dockerfile: Roogle.RoogleUrlConsumer/Dockerfile
    networks:
      - db-net
    secrets:
      - roogle_db_user
      - roogle_db_pass

  roogle.roogleindexer:
    image: ${DOCKER_REGISTRY-}roogleroogleindexer
    build:
      context: .
      dockerfile: Roogle.RoogleIndexer/Dockerfile
    networks:
      - db-net
    secrets:
      - roogle_db_user
      - roogle_db_pass

  roogle.rooglepageranker:
    image: ${DOCKER_REGISTRY-}rooglerooglepageranker
    build:
      context: .
      dockerfile: Roogle.RooglePageRanker/Dockerfile
    networks:
      - db-net
    secrets:
      - roogle_db_user
      - roogle_db_pass

  roogle.rooglespiderfeeder:
    image: ${DOCKER_REGISTRY-}rooglerooglespiderfeeder
    build:
      context: .
      dockerfile: Roogle.RoogleSpiderFeeder/Dockerfile
    networks:
      - db-net
    secrets:
      - roogle_db_user
      - roogle_db_pass

  roogle.rooglefrontend:
    image: ${DOCKER_REGISTRY-}rooglerooglefrontend
    build:
      context: .
      dockerfile: Roogle.RoogleFrontend/Dockerfile
    ports:
      - 15020:80
    networks:
      - db-net
    secrets:
      - roogle_db_user
      - roogle_db_pass

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - db-net

  rabbit-mq:
    image: rabbitmq:3.9-management
    ports:
      - "15672:15672" # ui port
      - "5672:5672"
    networks:
      - db-net

networks:
  db-net:

secrets:
  roogle_db_user:
    file: ./Secrets/roogle_db_user.txt
  roogle_db_pass:
    file: ./Secrets/roogle_db_pass.txt
